### ISSUE TITLE
Archive the logo in the artwork repo

### ISSUE THREAD

**Issue by palash25** [p-society/typeracer-cli#10]
@knrt10 love the logo can you please store it over here in our artwork repository. This will contain the collection of all the logos and posters related to our projects and sessions. 

I also plan to put them all up on behance and dribble along the lines of our community outreach programme.

https://github.com/p-society/artwork/tree/master/logos

**Comment by palash25** [comment]
In a separate folder like logos/projects/

**Comment by knrt10** [comment]
@palash25 did you add the logo? Can I close this issue?

**Comment by palash25** [comment]
Did you send me the edited logo? No point of adding the one that we are going to deprecate.

**Comment by knrt10** [comment]
Cool. Will send you the latest by today and then close this.

**Comment by knrt10** [comment]
Is it done @IamRaviTejaG ?

**Comment by palash25** [comment]
Closing it he said he will do it by tonight.
