### ISSUE TITLE
'typerace' leaves the terminal session unresponsive

### ISSUE THREAD

**Issue by IamRaviTejaG** [p-society/typeracer-cli#12]
Running `typerace` simply renders the terminal unresponsive.

**OS:**
Windows 10 Home Build 1803.

**Current Behavior:**
When `typerace` is run, the terminal session becomes unresponsive. Even `Ctrl-C` won't work.

**Expected Behavior:**
`typerace` should throw in a list of all commands (simply what `typerace -h` does now).

**Screenshot:**
![capture](https://user-images.githubusercontent.com/4240489/39750012-c4be4aec-52d1-11e8-81f7-31c2045cac40.JPG)

**Comment by knrt10** [comment]
@IamRaviTejaG  Thanks for opening this issue .Let me look into it.

**Comment by IamRaviTejaG** [comment]
@knrt10 Review and merge!

**Comment by IamRaviTejaG** [comment]
@knrt10 Been pushing to the master branch directly, instead of doing it on my fork and pushing it here. Hehe.

Anyway, closing issue. 😄
