### ISSUE TITLE
para.json: Remove all lengthy paragraphs

### ISSUE THREAD

**Issue by IamRaviTejaG** [p-society/typeracer-cli#27]
Paragraphs with ID 01-20 (excluding 11 & 14) need to be removed from `para.json` for they are very long.

PS: Those were my initial contributions, hearty apologies for that.

**Comment by palash25** [comment]
They are not very long and even if they are I don't think that you should delete them the online typeracer throws you some really long paras so why should we exclude them from ours?

**Comment by IamRaviTejaG** [comment]
@palash25 Our tool contains small paragraphs. That's why I suggested removing the really longer ones.

**Comment by palash25** [comment]
But the original game has both so why not keep both since we want to provide the same experience on the shell. cc @knrt10

**Comment by IamRaviTejaG** [comment]
I'm cool with that too. 😄

**Comment by knrt10** [comment]
@IamRaviTejaG paragraph given to user is never small cause if length of paragraph is less than 100 letters it combines with latter paragraph to make it big. So no worries in removing paras 1-20. Hope you cool with that? For more info refer to this https://github.com/p-society/typeracer-cli/blob/master/online/server.js#L36

**Comment by IamRaviTejaG** [comment]
@knrt10 Yeah, I'm definitely cool with that. 😃
